# Generated by Django 5.1.4 on 2024-12-27 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="post",
            unique_together={("title", "author")},
        ),
    ]
